compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

logFilters:
  - level: discard
    pattern: "react is listed by your project with version 18.2.0, which doesn't satisfy what native-base (p1eae0) and other dependencies request (but they have non-overlapping ranges!)."
  - level: discard
    text: "@ukdanceblue/mobile@workspace:packages/mobile doesn't provide @types/react-native (pbd1d9), requested by native-base."
  - level: discard
    text: "@ukdanceblue/mobile@workspace:packages/mobile doesn't provide react-dom (p855c6), requested by native-base."
