# For now this compose file is strictly for testing the server locally

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: danceblue
      POSTGRES_PASSWORD: danceblue
      POSTGRES_DB: danceblue
    networks:
      - danceblue
    attach: false
    volumes:
      - ./compose-volumes/postgres:/var/lib/postgresql/data
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    networks:
      - danceblue
    depends_on:
      - postgres
    env_file: ./packages/server/.env
    environment:
      DB_HOST: postgres
      DB_NAME: danceblue
      DB_UNAME: danceblue
      DB_PWD: danceblue
      NODE_ENV: development
      APPLICATION_HOST: server
      DATABASE_URL: postgres://danceblue:danceblue@postgres:5432/danceblue
  portal:
    container_name: portal
    build:
      context: ./packages/portal
      dockerfile: ./packages/portal/Dockerfile

networks:
  danceblue:
    driver: bridge
