# For now this compose file is strictly for testing the server locally

services:
  postgres:
    container_name: danceblue-database-${SUBDOMAIN:?error}
    image: postgres:16
    networks:
      - database
    environment:
      POSTGRES_USER: danceblue
      POSTGRES_PASSWORD: danceblue
      POSTGRES_DB: danceblue
    attach: false
    volumes:
      - database:/var/lib/postgresql/data
  server:
    container_name: danceblue-server-${SUBDOMAIN:?error}
    pull_policy: build
    build:
      context: .
      target: server
    networks:
      - proxy
      - database
    depends_on:
      - postgres
    env_file: ${ENV_PATH:-./packages/server/.env}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MS_OIDC_URL: https://login.microsoftonline.com/2b30530b-69b6-4457-b818-481cb53d42ae/v2.0/.well-known/openid-configuration
      SERVE_PATH: /data/local-uploads
      UPLOAD_PATH: /data/local-uploads
      MAX_FILE_SIZE: 200
      LOG_DIR: /data/logs
      DATABASE_URL: postgres://danceblue:danceblue@danceblue-database-${SUBDOMAIN:?error}:5432/danceblue
      SERVE_ORIGIN: http://localhost:8000
    volumes:
      - content:/data/local-uploads
  portal:
    container_name: danceblue-portal-${SUBDOMAIN:?error}
    pull_policy: build
    networks:
      - proxy
    build:
      context: .
      target: portal

networks:
  database:
    internal: true
  proxy:
    external: true
    name: proxy

volumes:
  content:
    driver: local
    name: danceblue-server-${SUBDOMAIN:?error}-content
  database:
    driver: local
    name: danceblue-server-${SUBDOMAIN:?error}-database
