# For now this compose file is strictly for testing the server locally

services:
  postgres:
    container_name: danceblue-app-database-${SUBDOMAIN:?error}
    image: postgres:latest
    environment:
      POSTGRES_USER: danceblue
      POSTGRES_PASSWORD: danceblue
      POSTGRES_DB: danceblue
    networks:
      - database
    attach: false
    volumes:
      - ./compose-volumes/postgres:/var/lib/postgresql/data
  server:
    container_name: danceblue-app-server-${SUBDOMAIN:?error}
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    networks:
      - database
      - proxy
    depends_on:
      - postgres
    env_file: ./packages/server/.env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      APPLICATION_PORT: 8000
      MS_OIDC_URL: https://login.microsoftonline.com/2b30530b-69b6-4457-b818-481cb53d42ae/v2.0/.well-known/openid-configuration
      SERVE_PATH: /data/local-uploads
      UPLOAD_PATH: /data/local-uploads
      MAX_FILE_SIZE: 200
      LOG_DIR: /data/logs
      DB_HOST: postgres
      DB_NAME: danceblue
      DB_UNAME: danceblue
      DB_PWD: danceblue
      APPLICATION_HOST: danceblue-app-server-${SUBDOMAIN:?error}
      DATABASE_URL: postgres://danceblue:danceblue@postgres:5432/danceblue
    volumes:
      - danceblue-app-server-${SUBDOMAIN:?error}-data:/data:rw
  portal:
    container_name: danceblue-app-portal-${SUBDOMAIN:?error}
    networks:
      - proxy
    build:
      context: ./packages/portal
      dockerfile: ./packages/portal/Dockerfile

networks:
  database:
  proxy:
    external: true
    name: proxy
