# For now this compose file is strictly for testing the server locally

services:
  postgres:
    container_name: danceblue-database-${SUBDOMAIN:?error}
    image: postgres:16
    networks:
      - database
    environment:
      POSTGRES_USER: danceblue
      POSTGRES_PASSWORD: danceblue
      POSTGRES_DB: danceblue
    attach: false
    volumes:
      - database:/var/lib/postgresql/data
  server:
    container_name: danceblue-server-${SUBDOMAIN:?error}
    build:
      context: .
      target: server
    image: ghcr.io/ukdanceblue/app-server:${VERSION:-latest}
    networks:
      - proxy
      - database
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      SERVE_PATH: /data/local-uploads
      UPLOAD_PATH: /data/local-uploads
      MAX_FILE_SIZE: 200
      LOG_DIR: /data/logs
      DATABASE_URL: postgres://danceblue:danceblue@danceblue-database-${SUBDOMAIN:?error}:5432/danceblue
      SERVE_ORIGIN: http://localhost:8000
      LOGGING_LEVEL: ${LOGGING_LEVEL:-info}
      APPLICATION_PORT: ${APPLICATION_PORT}
      APPLICATION_HOST: ${APPLICATION_HOST}
    secrets:
      - cookie_secret
      - jwt_secret
      - ms_client_id
      - ms_client_secret
      - expo_access_token
      - dbfunds_api_origin
      - dbfunds_api_key
    volumes:
      - content:/data/local-uploads
  portal:
    container_name: danceblue-portal-${SUBDOMAIN:?error}
    image: ghcr.io/ukdanceblue/app-portal:${VERSION:-latest}
    networks:
      - proxy
    build:
      context: .
      target: portal

networks:
  database:
    internal: true
  proxy:
    external: true
    name: proxy

volumes:
  content:
    driver: local
    name: danceblue-server-${SUBDOMAIN:?error}-content
  database:
    driver: local
    name: danceblue-server-${SUBDOMAIN:?error}-database

# Secrets from environment variables (i.e. var: environment: VAR)
# secrets:
#   token:
#     environment: "OAUTH_TOKEN"

secrets:
  cookie_secret:
    environment: "COOKIE_SECRET"
  jwt_secret:
    environment: "JWT_SECRET"
  ms_client_id:
    environment: "MS_CLIENT_ID"
  ms_client_secret:
    environment: "MS_CLIENT_SECRET"
  expo_access_token:
    environment: "EXPO_ACCESS_TOKEN"
  dbfunds_api_origin:
    environment: "DBFUNDS_API_ORIGIN"
  dbfunds_api_key:
    environment: "DBFUNDS_API_KEY"
