# For now this compose file is strictly for testing the server locally

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: danceblue
      POSTGRES_PASSWORD: danceblue
      POSTGRES_DB: danceblue
    networks:
      - danceblue
    attach: false
    volumes:
      - danceblue-server-postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - 8000:8000
    networks:
      - danceblue
    depends_on:
      - postgres
    env_file: ./packages/server/.env
    environment:
      DB_HOST: postgres
      DB_NAME: danceblue
      DB_UNAME: danceblue
      DB_PWD: danceblue
      NODE_ENV: development
      APPLICATION_HOST: server
    command: ["node", "dist/index.js", "--migrate-db"]
  portal:
    container_name: portal
    build:
      context: .
      dockerfile: ./packages/portal/Dockerfile
      args:
        - VITE_APP_API_BASE_URL=http://localhost:8000
    ports:
      - 3000:80

networks:
  danceblue:
    driver: bridge

volumes:
  danceblue-server-postgres-data:
