name: EAS Update

on:
  pull_request:
    branches: ["main"]
    paths:
      - "packages/common/**"
      - "packages/mobile/**"
      - "yarn.lock"
      - ".yarnrc.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node 18.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies (commmon)
        working-directory: ./packages/commmon
        run: yarn install

      - name: Install dependencies (mobile)
        working-directory: ./packages/mobile
        run: yarn install

      - name: Build GraphQL
        run: yarn run gql:build
        working-directory: .

      - name: Build common
        run: yarn run build
        working-directory: ./packages/common

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command:
            eas update --auto --branch ${{ github.event.pull_request.head.ref }}
