# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches:
      - main
    paths:
      [
        "packages/**",
        "eslint.config.js",
        "graphql.config.json",
        "package.json",
        "yarn.lock",
        ".yarnrc.yml",
        "codegen.ts",
        "tsconfig.json",
        ".github/workflows/eslint.yml"
      ]
  pull_request:
    branches:
      - main
    paths:
      [
        "packages/**",
        "eslint.config.js",
        "graphql.config.json",
        "package.json",
        "yarn.lock",
        ".yarnrc.yml",
        "codegen.ts",
        "tsconfig.json",
      ]
  workflow_call:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Enable Corepack before setting up Node
        run: corepack enable

      - name: Set up node 22.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: yarn

      - name: Install ESLint
        run: |
          yarn add @microsoft/eslint-formatter-sarif@3.1.0

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: yarn run server:prisma generate

      - name: Build common
        run: yarn run common:build

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: yarn repo:lint
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
