name: Promote Staging

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 or 2 AM Eastern Time
    - cron: "0 6 * * *"

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  do-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Promote release
        run: ./scripts/promote-branch.sh staging release
