name: Promote Staging

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 or 2 AM Eastern Time
    - cron: "0 6 * * *"

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

# All this job does is fast forward the release branch to the latest commit on staging
jobs:
  do-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release
          ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Promote release
        run: |
          ls
          ./scripts/promote-branch.sh main staging
