name: Stage Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ukdanceblue/app-server

jobs:
  check:
    uses: ./.github/workflows/check.yml
  stage-release:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release
          ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Promote release
        working-directory: .
        run: |
          ls -la
          pwd
          ls ..
          ls ../..
          ./scripts/promote-branch.sh main staging
